// A practical country list for the onboarding "What country do you study
// in?" step. Not exhaustive ISO-3166, but covers the vast majority of
// students — sorted alphabetically with a few common ones pinned to top.

export const COUNTRIES: string[] = [
  "United Kingdom",
  "United States",
  "Cyprus",
  "Greece",
  "Ireland",
  "Australia",
  "Canada",
  "Austria",
  "Belgium",
  "Brazil",
  "Bulgaria",
  "China",
  "Croatia",
  "Czech Republic",
  "Denmark",
  "Egypt",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Israel",
  "Italy",
  "Japan",
  "Jordan",
  "Kenya",
  "Latvia",
  "Lebanon",
  "Lithuania",
  "Luxembourg",
  "Malaysia",
  "Malta",
  "Mexico",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Saudi Arabia",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Thailand",
  "Turkey",
  "Ukraine",
  "United Arab Emirates",
  "Vietnam",
  "Other",
];
